import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
plt.figure(figsize=(10, 6))
plt.title("Missing Values Heatmap")
plt.show()
plt.suptitle("Feature Distributions", fontsize=16)
plt.show()
plt.figure(figsize=(24, 24))
plt.title("Feature Correlation Heatmap")
plt.show()
plt.figure(figsize=(10, 6))
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()
print(classification_report(y_validation,pred))
plt.figure(figsize=(10, 6))
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()
print(classification_report(y_validation,y_pred))
plt.figure(figsize=(10, 6))
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()
print(classification_report(y_validation,y_pred))
print(classification_report(y_validation,y_pred))
print(classification_report(y_validation,y_pred))
from sklearn.metrics import confusion_matrix, accuracy_score
print(classification_report(y_validation,y_pred))
from sklearn.metrics import confusion_matrix, accuracy_score
print(classification_report(y_validation, pred))